# Generated by Django 4.0.5 on 2022-06-11 12:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Patients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('full_name', models.CharField(max_length=128)),
                ('NationalID', models.CharField(max_length=64)),
                ('birth_date', models.DateField()),
                ('phone', models.CharField(max_length=32)),
                ('reception', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Diagnosis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Temperature', models.DecimalField(decimal_places=1, max_digits=3)),
                ('Pressure', models.CharField(max_length=32)),
                ('sitDescription', models.TextField()),
                ('drDiagnosis', models.TextField(blank=True)),
                ('iscompleted', models.BooleanField(blank=True, default=False)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='doctor', to=settings.AUTH_USER_MODEL)),
                ('nurce', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('patients', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.patients')),
            ],
        ),
    ]
